-- ============================================================
-- IAS IQ — Supabase schema
-- Run this once in your Supabase project: SQL Editor → New query → paste → Run
-- ============================================================

-- 1) Daily question sets (one row per date, generated by the GitHub Actions cron)
create table if not exists questions_daily (
  id uuid primary key default gen_random_uuid(),
  date date unique not null,
  questions jsonb not null,       -- array of question objects (see schema below)
  created_at timestamptz default now()
);

-- 2) Each user's attempt at a given day's test
create table if not exists attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  date date not null,
  score int not null,
  total int not null,
  correct int not null,
  wrong int not null,
  skipped int not null,
  answers jsonb not null,             -- e.g. ["C","A",null,"B",...]
  questions_snapshot jsonb not null,  -- full question set at time of attempt (for dashboard review)
  created_at timestamptz default now(),
  unique(user_id, date)               -- one attempt per user per day
);

-- ---------------- Row Level Security ----------------

alter table questions_daily enable row level security;
alter table attempts enable row level security;

-- Any logged-in user can read the daily question sets
create policy "Authenticated users can read questions"
  on questions_daily for select
  to authenticated
  using (true);

-- Only the GitHub Actions cron (using the service_role key, which bypasses RLS)
-- writes to questions_daily — no insert/update policy needed for normal users.

-- Users can only see their own attempts
create policy "Users can read own attempts"
  on attempts for select
  to authenticated
  using (auth.uid() = user_id);

-- Users can only insert attempts as themselves
create policy "Users can insert own attempts"
  on attempts for insert
  to authenticated
  with check (auth.uid() = user_id);

-- ---------------- Question JSON shape (for reference) ----------------
-- {
--   "number": "Question 1 of 15",
--   "text": "Consider the following statements regarding ...",
--   "statements": ["...", "..."],
--   "followup": "Which of the statements given above is/are correct?",
--   "options": [["A","..."], ["B","..."], ["C","..."], ["D","..."]],
--   "correct": "C",
--   "correctText": "C) Both 1 and 2",
--   "explanation": "<strong>Explanation:</strong> ..."
-- }
